import { Resend } from 'resend';
import { TTKH, XuLiMailPayload } from '@/lib/types/email.types';

// 1. Initialize inside a getter or check to prevent "Missing API key" crash
const getResendClient = () => {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
        throw new Error("RESEND_API_KEY is not defined in your environment variables.");
    }
    return new Resend(apiKey);
};

export function importFile(file: File) {
    const allowedTypes = ['application/pdf', 'image/jpeg', 'image/png'];
    if (!allowedTypes.includes(file.type)) {
        throw new Error('Unsupported file type');
    }
    return file;
}

/**
 * SendMail() — Sends email using Resend
 * @param ttkh - The Customer information (contains Email and Name)
 * @param payload - The Email payload (contains the message and optional file)
 */
export async function sendMail(ttkh: TTKH, payload: XuLiMailPayload) {
    const resend = getResendClient();
    const attachments = [];

    // Handle File Attachment
    if (payload.File) {
        const buffer = Buffer.from(await payload.File.arrayBuffer());
        attachments.push({
            filename: payload.File.name,
            content: buffer,
        });
    }

    try {
        const data = await resend.emails.send({
            from: 'Your Company <onboarding@resend.dev>', // Ensure this domain is verified in Resend
            to: [ttkh.Email], // Resend expects an array or string
            subject: `Thư gửi tới ${ttkh.TenKH}`,
            // payload.Mail should contain the text/HTML generated by your other function
            html: `<div>${payload.Mail.replace(/\n/g, '<br>') || 'No content provided'}</div>`,
            attachments,
        });

        return { success: true, data };
    } catch (error) {
        console.error("Failed to send email:", error);
        return { success: false, error };
    }
}